# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import marklogic_pb2 as marklogic__pb2


class MarkLogicServiceStub(object):
    """MarkLogic service definition for document operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertDocument = channel.unary_unary(
                '/marklogic.MarkLogicService/InsertDocument',
                request_serializer=marklogic__pb2.DocumentRequest.SerializeToString,
                response_deserializer=marklogic__pb2.DocumentResponse.FromString,
                )


class MarkLogicServiceServicer(object):
    """MarkLogic service definition for document operations
    """

    def InsertDocument(self, request, context):
        """Insert a document into MarkLogic database
        Accepts any valid JSON object and returns operation status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarkLogicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertDocument,
                    request_deserializer=marklogic__pb2.DocumentRequest.FromString,
                    response_serializer=marklogic__pb2.DocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marklogic.MarkLogicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarkLogicService(object):
    """MarkLogic service definition for document operations
    """

    @staticmethod
    def InsertDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/marklogic.MarkLogicService/InsertDocument',
            marklogic__pb2.DocumentRequest.SerializeToString,
            marklogic__pb2.DocumentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
