# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: marklogic.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmarklogic.proto\x12\tmarklogic\"\xbc\x01\n\x0f\x44ocumentRequest\x12\x11\n\tjson_data\x18\x01 \x01(\t\x12\x14\n\x0c\x64ocument_uri\x18\x02 \x01(\t\x12\x13\n\x0b\x63ollections\x18\x03 \x03(\t\x12:\n\x08metadata\x18\x04 \x03(\x0b\x32(.marklogic.DocumentRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"f\n\x10\x44ocumentResponse\x12\x16\n\x0estatus_message\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x12\x14\n\x0c\x64ocument_uri\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x04 \x01(\t2]\n\x10MarkLogicService\x12I\n\x0eInsertDocument\x12\x1a.marklogic.DocumentRequest\x1a\x1b.marklogic.DocumentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'marklogic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DOCUMENTREQUEST_METADATAENTRY']._options = None
  _globals['_DOCUMENTREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_DOCUMENTREQUEST']._serialized_start=31
  _globals['_DOCUMENTREQUEST']._serialized_end=219
  _globals['_DOCUMENTREQUEST_METADATAENTRY']._serialized_start=172
  _globals['_DOCUMENTREQUEST_METADATAENTRY']._serialized_end=219
  _globals['_DOCUMENTRESPONSE']._serialized_start=221
  _globals['_DOCUMENTRESPONSE']._serialized_end=323
  _globals['_MARKLOGICSERVICE']._serialized_start=325
  _globals['_MARKLOGICSERVICE']._serialized_end=418
# @@protoc_insertion_point(module_scope)
